# version: "3"

services:
  db:
    image: mariadb:10.6.17-focal
    environment:
      MYSQL_ROOT_PASSWORD: abc123!
      MYSQL_USER: fauser
      MYSQL_PASSWORD: abc123!
      MYSQL_DATABASE: fastapi
    ports:
      - 3306:3306
    volumes:
      - md_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d

  web:
    image: redraoh/fawebapp
    build: web
    ports:
      - 8000:8000
    environment:
      DB_HOST: db
      DB_USER: fauser
      DB_PASSWORD: abc123!
      DB_NAME: fastapi
    depends_on: # db가 만들어지기 전까지는 실행되지않는다. 기다리면 DB_HOST값을 가져올 수 있음
      - db

  nginx:
    build: nginx
    ports:
      - 80:80
    depends_on:
      - web
#     web:
#       condition: service_completed_successfully
volumes:
  md_data: